//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermanDelivery.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_h {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_h() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupermanDelivery.Resx.AppResources.h", typeof(AppResources_h).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शहर.
        /// </summary>
        internal static string CityText {
            get {
                return ResourceManager.GetString("CityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नंबर.
        /// </summary>
        internal static string DriverDetailDriverNumber {
            get {
                return ResourceManager.GetString("DriverDetailDriverNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कमाई शुरू करने के लिए कृपया नीचे विवरण भरें.
        /// </summary>
        internal static string DriverDetailHeading {
            get {
                return ResourceManager.GetString("DriverDetailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालिक का नाम.
        /// </summary>
        internal static string DriverDetailOwnerName {
            get {
                return ResourceManager.GetString("DriverDetailOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालिक का नंबर.
        /// </summary>
        internal static string DriverDetailOwnerNumber {
            get {
                return ResourceManager.GetString("DriverDetailOwnerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आगे बढ़ना.
        /// </summary>
        internal static string DriverDetailProceedBtnText {
            get {
                return ResourceManager.GetString("DriverDetailProceedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वाहन का प्रकार.
        /// </summary>
        internal static string DriverDetailVehicleType {
            get {
                return ResourceManager.GetString("DriverDetailVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सुपरमैन में आपका स्वागत है!.
        /// </summary>
        internal static string SupermanWelcomeText {
            get {
                return ResourceManager.GetString("SupermanWelcomeText", resourceCulture);
            }
        }
    }
}
