//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermanDelivery.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupermanDelivery.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Side.
        /// </summary>
        public static string BackSideText {
            get {
                return ResourceManager.GetString("BackSideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityText {
            get {
                return ResourceManager.GetString("CityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s Number.
        /// </summary>
        public static string DriverDetailDriverNumber {
            get {
                return ResourceManager.GetString("DriverDetailDriverNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill below details to start earning.
        /// </summary>
        public static string DriverDetailHeading {
            get {
                return ResourceManager.GetString("DriverDetailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Name.
        /// </summary>
        public static string DriverDetailOwnerName {
            get {
                return ResourceManager.GetString("DriverDetailOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Number.
        /// </summary>
        public static string DriverDetailOwnerNumber {
            get {
                return ResourceManager.GetString("DriverDetailOwnerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEED.
        /// </summary>
        public static string DriverDetailProceedBtnText {
            get {
                return ResourceManager.GetString("DriverDetailProceedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string DriverDetailVehicleType {
            get {
                return ResourceManager.GetString("DriverDetailVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Side.
        /// </summary>
        public static string FrontSideText {
            get {
                return ResourceManager.GetString("FrontSideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Superman!.
        /// </summary>
        public static string SupermanWelcomeText {
            get {
                return ResourceManager.GetString("SupermanWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm things like Names, Numbers, Addresses are clearly visible while taking photo.
        /// </summary>
        public static string UploadDocIDTipText {
            get {
                return ResourceManager.GetString("UploadDocIDTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Aadhar or Voter ID.
        /// </summary>
        public static string UploadDocOwnerIDText {
            get {
                return ResourceManager.GetString("UploadDocOwnerIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license.
        /// </summary>
        public static string UploadVehicleDrivingLicenseText {
            get {
                return ResourceManager.GetString("UploadVehicleDrivingLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s RC.
        /// </summary>
        public static string UploadVehicleRCText {
            get {
                return ResourceManager.GetString("UploadVehicleRCText", resourceCulture);
            }
        }
    }
}
